server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_online_edu?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME:your_mysql_username}
    password: ${MYSQL_PASSWORD:your_mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
